---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/orca-slicer/

patches:
  - target:
      kind: Deployment
      name: orca-slicer
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/linuxserver/orcaslicer:2.3.0@sha256:a949c0cdd27c3c996b0b2907c04f12461a9ccbfc6e7c4832fbe476a77c3f3bab