---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/orca-slicer/

patches:
  - target:
      kind: Deployment
      name: orca-slicer
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/linuxserver/orcaslicer:2.3.0@sha256:b5f8785643ed966e7d01cc681d13336d1d6f41a42b2a9e252a871c42d8e38b04